blog/urls.py
from django.conf.urls import url

from . import views

app_name = 'blog'
urlpatterns = [
	url(r'^$', views.IndexView.as_view(), name='index'),
	url(r'^post/(?P<pk>[0-9]+)/$', views.detail, name='detail'),
	url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.archives, name='archives'),
	url(r'^category/(?P<pk>[0-9]+)/$', views.CategoryView.as_view(), name='category'),
	url(r'^tag/(?P<pk>[0-9]+)/$', views.TagView.as_view(), name='tag'),
	#url(r'^search/$', views.search, name='search'),
]

comments/urls.py
from django.conf.urls import url
from . import views

app_name = 'comments'
urlpatterns = [
	url(r'^comment/post/(?P<post_pk>[0-9]+)/$', views.post_comment, name = 'post_comment'),
]

learn/urls.py
#from django.conf.urls import url
from django.conf.urls import url, include
from django.contrib import admin
from blog.feeds import AllPostsRssFeed

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('blog.urls')),
    url(r'', include('comments.urls')),
    url(r'^all/rss/$', AllPostsRssFeed(), name = 'rss'),
    url(r'^search/', include('haystack.urls')),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils.six import python_2_unicode_compatible
import markdown
from django.utils.html import strip_tags

# Create your models here.
@python_2_unicode_compatible
class Category(models.Model):
	name = models.CharField(max_length=100)

	def __str__(self):
		return self.name

@python_2_unicode_compatible
class Tag(models.Model):
	name = models.CharField(max_length=100)

	def __str__(self):
		return self.name

@python_2_unicode_compatible
class Post(models.Model):
	title = models.CharField(max_length=100)
	body = models.TextField()
	created_time = models.DateTimeField()
	modified_time = models.DateTimeField()
	excerpt = models.CharField(max_length=200, blank=True)
	category = models.ForeignKey(Category)
	tags = models.ManyToManyField(Tag, blank=True)
	author = models.ForeignKey(User)
	views = models.PositiveIntegerField(default=0)

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse('blog:detail', kwargs={'pk': self.pk})

	class Meta:
		ordering = ['-created_time']

	def increase_views(self):
		self.views += 1
		self.save(update_fields=['views'])

	def save(self, *args, **kwargs):
		if not self.excerpt:
			md = markdown.Markdown(extensions=[
				'markdown.extensions.extra',
				'markdown.extensions.codehilite',
				])
			self.excerpt = strip_tags(md.convert(self.body))[:108]
		super(Post, self).save(*args, **kwargs)

comments/models.py
from django.db import models
from django.utils.six import python_2_unicode_compatible

# Create your models here.
@python_2_unicode_compatible
class Comment(models.Model):
	name = models.CharField(max_length=100)
	email = models.EmailField(max_length=255)
	url = models.URLField(blank=True)
	text = models.TextField()
	created_time = models.DateTimeField(auto_now_add=True)

	post = models.ForeignKey('blog.Post')

	def __str__(self):
		return self.text[:20]

comments/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
	class Meta:
		model = Comment
		fields = ['name', 'email', 'url', 'text']

blog/views.py
#coding: utf-8
#Create your views here.

import markdown
from django.shortcuts import render, get_object_or_404
from comments.forms import CommentForm
from .models import Post, Category, Tag
from django.views.generic import ListView
from django.db.models import Q


class IndexView(ListView):
  model = Post
  template_name = 'blog/index.html'
  context_object_name = 'post_list'


def detail(request, pk):
    post = get_object_or_404(Post, pk=pk)

    post.increase_views()

    post.body = markdown.markdown(post.body,
                                  extensions=[
                                      'markdown.extensions.extra',
                                      'markdown.extensions.codehilite',
                                      'markdown.extensions.toc',
                                  ])
    form = CommentForm()
    comment_list = post.comment_set.all()
    context = {'post': post,
                'form': form,
                'comment_list': comment_list
              }
    return render(request, 'blog/detail.html', context=context)

def archives(request, year, month):
    post_list = Post.objects.filter(created_time__year=year,
                                    created_time__month=month,
                                    )
    return render(request, 'blog/index.html', context={'post_list': post_list})

class CategoryView(IndexView):
  def get_queryset(self):
    cate = get_object_or_404(Category, pk = self.kwargs.get('pk'))
    return super(CategoryView, self).get_queryset().filter(category=cate)

class TagView(ListView):
    model = Post
    template_name = 'blog/index.html'
    context_object_name = 'post_list'

    def get_queryset(self):
        tag = get_object_or_404(Tag, pk=self.kwargs.get('pk'))
        return super(TagView, self).get_queryset().filter(tags=tag)


class IndexView(ListView):
  model = Post
  template_name = 'blog/index.html'
  context_object_name = 'post_list'
  paginate_by = 10

  def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)
    paginator = context.get('paginator')
    page = context.get('page_obj')
    is_paginated = context.get('is_paginated')
    pagination_data = self.pagination_data(paginator, page, is_paginated)
    context.update(pagination_data)
    return context

  def pagination_data(self, paginator, page, is_paginated):
    if not is_paginated:
      return {}

    left = []
    right = []

    left_has_more = False
    right_has_more = False
    first = False
    last = False

    page_number = page.number
    total_pages = paginator.num_pages

    page_range = paginator.page_range
    if page_number == 1:
      right = page_range[page_number:page_number + 2]
      if right[-1] < total_pages - 1:
        right_has_more = True
      if right[-1] < total_pages:
        last = True

    elif page_number == total_pages:
      left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0:page_number - 1]

      if left[0] > 2:
        left_has_more = True

      if left[0] > 1:
        first = True
    
    else:
      left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0:page_number - 1]
      right = page_range[page_number:page_number + 2]

      if right[-1] < total_pages - 1:
        right_has_more = True
      if right[-1] < total_pages:
        last = True

      if left[0] > 2:
        left_has_more = True
      if left[0] > 1:
        first = True
    data = {
      'left': left,
      'right': right,
      'left_has_more': left_has_more,
      'right_has_more': right_has_more,
      'first': first,
      'last': last,
    }

    return data

def search(request):
  q = request.GET.get('q')
  error_msg = ''

  if not q:
    error_msg = "请输入关键词"
    return render(request, 'blog/index.html', {'error_msg': error_msg})

  post_list = Post.objects.filter(Q(title__icontains=q) | Q(body__icontains=q))
  return render(request, 'blog/index.html', {'error_msg': error_msg,
                                             'post_list': post_list})

comments/views.py
from django.shortcuts import render, get_object_or_404, redirect
from blog.models import Post

from .models import Comment
from .forms import CommentForm

# Create your views here.

def post_comment(request, post_pk):
	post = get_object_or_404(Post, pk=post_pk)
	if request.method == 'POST':
		form = CommentForm(request.POST)
		if form.is_valid():
			comment = form.save(commit=False)
			comment.post = post
			comment.save()
			return redirect(post)

		else:
			comment_list = post.comment_set.all()
			context = {'post': post,
						'form': form,
						'comment_list': comment_list
						}
			return render(request, 'blog/detail.html', context=context)
	return redirect(post)

templates/base.html
{% load staticfiles %}
{% load blog_tags %}
<!DOCTYPE html>
<html>
<head>
    <title>{{ post.title }} - 我的博客</title>

    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="keywords" content="{{ post.title }}"/>
    <meta name="description" content="{{ post.excerpt }}"/>

    <!-- css -->
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="{% static 'blog/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/pace.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/custom.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/highlights/github.css' %}">

    <!-- js -->
    <script src="{% static 'blog/js/jquery-2.1.3.min.js' %}"></script>
    <script src="{% static 'blog/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'blog/js/pace.min.js' %}"></script>
    <script src="{% static 'blog/js/modernizr.custom.js' %}"></script>
    <style>
        span.highlighted {
            color: red;
        }
    </style>
</head>

<body>
<div class="container">
    <header id="site-header">
        <div class="row">
            <div class="col-md-4 col-sm-5 col-xs-8">
                <div class="logo">
                    <h1><a href="{% url 'blog:index' %}">我的博客</a></h1>
                </div>
            </div><!-- col-md-4 -->
            <div class="col-md-8 col-sm-7 col-xs-4">
                <nav class="main-nav" role="navigation">
                    <div class="navbar-header">
                        <button type="button" id="trigger-overlay" class="navbar-toggle">
                            <span class="ion-navicon"></span>
                        </button>
                    </div>

                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="cl-effect-11"><a href="{% url 'blog:index' %}" data-hover="首页">首页</a></li>
                            <li class="cl-effect-11"><a href="full-width.html" data-hover="博客">博客</a></li>
                            <li class="cl-effect-11"><a href="about.html" data-hover="关于">关于</a></li>
                            <li class="cl-effect-11"><a href="contact.html" data-hover="联系">联系</a></li>
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </nav>
                <div id="header-search-box">
                    <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
                    <div id="search-form" class="search-form">
                        <form role="search" method="get" id="searchform" action="{% url 'haystack_search' %}">
                          <input type="search" name="q" placeholder="搜索" required>
                          <button type="submit"><span class="ion-ios-search-strong"></span></button>
                        </form>
                    </div>
                </div>
            </div><!-- col-md-8 -->
        </div>
    </header>
</div>

<div class="content-body">
    <div class="container">
        <div class="row">
            <main class="col-md-8">
                {% block main %}
                {% endblock main %}
            </main>
            <aside class="col-md-4">
                <div class="widget widget-recent-posts">
                    <h3 class="widget-title">最新文章</h3>
                    {% get_recent_posts as recent_post_list %}
                    <ul>
                        {% for post in recent_post_list %}
                        <li>
                            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                        </li>
                        {% empty %}
                        暂无文章！
                        {% endfor %}
                    </ul>
                </div>
                <div class="widget widget-archives">
                    <h3 class="widget-title">归档</h3>
                    {% archives as date_list %}
                    <ul>
                        {% for date in date_list %}
                        <li>
                            <a href="{% url 'blog:archives' date.year date.month %}">
                                {{ date.year }} 年 {{ date.month }} 月</a>
                        </li>
                        {% empty %}
                        暂无归档！
                        {% endfor %}
                    </ul>
                </div>

                <div class="widget widget-category">
                    <h3 class="widget-title">分类</h3>
                    {% get_categories as category_list %}
                    <ul>
                        {% for category in category_list %}
                        <li>
                            <a href="{% url 'blog:category' category.pk %}">{{ category.name }}<span class="post-count">({{ category.num_posts }})</span></a>
                        </li>
                        {% empty %}
                        暂无分类！
                        {% endfor %}
                    </ul>
                </div>

                <div class="widget widget-tag-cloud">
                    <h3 class="widget-title">标签云</h3>
                    {% get_tags as tag_list %}
                    <ul>
                        {% for tag in tag_list %}
                        <li>
                            <a href="{% url 'blog:tag' tag.pk %}">{{ tag.name }}</a>
                        </li>
                        {% empty %}
                        暂无标签
                        {% endfor %}
                    </ul>
                </div>
                <div class="rss">
                    <a href="{% url 'rss' %}"><span class="ion-social-rss-outline"></span> RSS 订阅</a>
                </div>
            </aside>
        </div>
    </div>
</div>
<footer id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="copyright">&copy; 2017 - 我的博客</p>
            </div>
        </div>
    </div>
</footer>

<!-- Mobile Menu -->
<div class="overlay overlay-hugeinc">
    <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
    <nav>
        <ul>
            <li><a href="index.html">首页</a></li>
            <li><a href="full-width.html">博客</a></li>
            <li><a href="about.html">关于</a></li>
            <li><a href="contact.html">联系</a></li>
        </ul>
    </nav>
</div>

<script src="{% static 'blog/js/script.js' %}"></script>

</body>
</html>

templates/blog/detail.html
{% extends 'base.html' %}

{% block main %}
<article class="post post-{{ post.pk }}">
      <header class="entry-header">
        <h1 class="entry-title">{{ post.title }}</h1>
        <div class="entry-meta">
          <span class="post-category"><a href="#">{{ post.category.name }}</a></span>
          <span class="post-date"><a href="#"><time class="entry-date"
                                                    datetime="{{ post.created_time }}">{{ post.created_time }}</time></a></span>
          <span class="post-author"><a href="#">{{ post.author }}</a></span>
          <span class="comments-link"><a href="#">{{ post.comment_set.count }} 评论</a></span>
          <span class="views-count"><a href="#">{{ post.views }} 阅读</a></span>
        </div>
      </header>
  <div class="entry-content clearfix">
    {{ post.body|safe }}
  </div>
</article>
    <section class="comment-area" id="comment-area">
                    <hr>
                    <h3>发表评论</h3>
                    <form action="{% url 'comments:post_comment' post.pk %}" method="post" class="comment-form">
                      {% csrf_token %}
                        <div class="row">
                            <div class="col-md-4">
                                <label for="{{ from.name.id_for_label }}">名字：</label>
                                {{ form.name }}
                                {{ form.name.errors }}
                            </div>
                            <div class="col-md-4">
                                <label for="{{ form.email.id_for_label }}">邮箱：</label>
                                {{ form.email }}
                                {{ form.email.errors }}
                            </div>
                            <div class="col-md-4">
                                <label for="{{ form.url.id_for_label }}">网址：</label>
                                {{ form.url}}
                                {{ form.url.errors }}
                            </div>
                            <div class="col-md-12">
                                <label for="{{ from.text.id_for_label }}">评论：</label>
                                {{ form.text }}
                                {{ form.text.errors }}
                                <button type="submit" class="comment-btn">发表</button>
                            </div>
                        </div>    <!-- row -->
                    </form>
                    <div class="comment-list-panel">
                        <h3>评论列表，共 <span>{{ post.comment_set.count }}</span> 条评论</h3>
                        <ul class="comment-list list-unstyled">
                          {% for comment in comment_list %}
                            <li class="comment-item">
                                <span class="nickname">{{ comment.name }}</span>
                                <time class="submit-date">{{ comment.created_time }}</time>
                                <div class="text">
                                    {{ comment.text }}
                                </div>
                            </li>
                            {% empty %}
                            暂无评论
                            {% endfor %}
                        </ul>
                    </div>
                </section>
{% endblock main %}
{% block toc %}
    <div class="widget widget-content">
        <h3 class="widget-title">文章目录</h3>
        <ul>
            <li>
                <a href="#">教程特点</a>
            </li>
            <li>
                <a href="#">谁适合这个教程</a>
            </li>
            <li>
                <a href="#">在线预览</a>
            </li>
            <li>
                <a href="#">资源列表</a>
            </li>
            <li>
                <a href="#">获取帮助</a>
            </li>
        </ul>
    </div>
{% endblock toc %}

templates/blog/index.html
{% extends 'base.html' %}

{% block main %}
    {% if error_msg %}
        <p>{{ error_msg }}</p>
    {% endif %}
    {% for post in post_list %}
    <article class="post post-{{ post.pk }}">
                <header class="entry-header">
                    <h1 class="entry-title">
                        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                    </h1>
                    <div class="entry-meta">
                        <span class="post-category">
                            <a href="{% url 'blog:category' post.category.pk %}">{{ post.category.name }}</a></span>
                        <span class="post-date"><time class="entry-date"
                                                                  datetime="{{ post.created_time }}">{{ post.created_time }}</time></a></span>
                        <span class="post-author">{{ post.author }}</span>
                        <span class="comments-link">{{ post.comment_set.count }} 评论</span>
                        <span class="views-count">{{ post.views }} 阅读</span>
                    </div>
                </header>
                <div class="entry-content clearfix">
                    <p>{{ post.excerpt }}...
                        <span class="read-more"><a href="{{ post.get_absolute_url }}" class="more-link">阅读全文 <span class="meta-nav">»</span></a></span>
                    </p>
                </div>
    </article>
    {% empty %}
        <div class="no-post">暂时还没有发布的文章！</div>
    {% endfor %}

    {% if is_paginated %}
    <div class="pagination">
      {% if first %}
        <a href="?page=1">1</a>
      {% endif %}
      {% if left %}
        {% if left_has_more %}
            <span>...</span>
        {% endif %}
        {% for i in left %}
            <a href="?page={{ i }}">{{ i }}</a>
        {% endfor %}
      {% endif %}
      <a href="?page={{ page_obj.number }}" style="color: red">{{ page_obj.number }}</a>
      {% if right %}
        {% for i in right %}
            <a href="?page={{ i }}">{{ i }}</a>
        {% endfor %}
        {% if right_has_more %}
            <span>...</span>
        {% endif %}
      {% endif %}
      {% if last %}
        <a href="?page={{ paginator.num_pages }}">{{ paginator.num_pages }}</a>
      {% endif %}
    </div>
    {% endif %}
{% endblock main %}

templates/search/search.html
{% extends 'base.html' %}
{% load highlight %}

{% block main %}
    {% if query %}
        {% for result in page.object_list %}
            <article class="post post-{{ result.object.pk }}">
                <header class="entry-header">
                    <h1 class="entry-title">
                        <a href="{{ result.object.get_absolute_url }}">{% highlight result.object.title with query %}</a>
                    </h1>
                    <div class="entry-meta">
                    <span class="post-category">
                        <a href="{% url 'blog:category' result.object.category.pk %}">
                            {{ result.object.category.name }}</a></span>
                        <span class="post-date"><a href="#">
                            <time class="entry-date" datetime="{{ result.object.created_time }}">
                                {{ result.object.created_time }}</time></a></span>
                        <span class="post-author"><a href="#">{{ result.object.author }}</a></span>
                        <span class="comments-link">
                        <a href="{{ result.object.get_absolute_url }}#comment-area">
                            {{ result.object.comment_set.count }} 评论</a></span>
                        <span class="views-count"><a
                                href="{{ result.object.get_absolute_url }}">{{ result.object.views }} 阅读</a></span>
                    </div>
                </header>
                <div class="entry-content clearfix">
                    <p>{% highlight result.object.body with query %}</p>
                    <div class="read-more cl-effect-14">
                        <a href="{{ result.object.get_absolute_url }}" class="more-link">继续阅读 <span
                                class="meta-nav">→</span></a>
                    </div>
                </div>
            </article>
        {% empty %}
            <div class="no-post">没有搜索到你想要的结果！</div>
        {% endfor %}
        {% if page.has_previous or page.has_next %}
            <div>
                {% if page.has_previous %}
                    <a href="?q={{ query }}&amp;page={{ page.previous_page_number }}">{% endif %}&laquo; Previous
                {% if page.has_previous %}</a>{% endif %}
                |
                {% if page.has_next %}<a href="?q={{ query }}&amp;page={{ page.next_page_number }}">{% endif %}Next
                &raquo;{% if page.has_next %}</a>{% endif %}
            </div>
        {% endif %}
    {% else %}
        请输入搜索关键词，例如 django
    {% endif %}
{% endblock main %}